### ISSUE TITLE
AOT compilation

### ISSUE THREAD

**Issue by benetis-bentley** [nsmolenskii/ng-demo-lib#3]
Hey, i like your workaround. But I can't seem to get AOT working, are you building with aot ng-demo-lib?

**Comment by nsmolenskii** [comment]
Hi @benetis-bentley. It works for me and my team very well with aot. 
Thanks for question, I will update readme.

P.S.: see a [live demo](https://nsmolenskii.github.io/ng-demo-app/) that based on aot build.

**Comment by benetis-bentley** [comment]
Thanks for answer. Going by your example - it works for me too (in demo-app equivalent). But I was wondering if it is possible to compile in demo lib scope. (just to catch aot compilation errors before they get to demo-app if they are developed independently)

**Comment by nsmolenskii** [comment]
Hi @benetis-bentley. Sure you can. Cause it is normal cli project, you could use it inside [sandbox app](https://github.com/nsmolenskii/ng-demo-lib/blob/master/demo-app/app).
Because of usage, you could try to run or build library project with aot flag.
